'''
Created on Dec 10, 2021

@author: Cyrus
'''

start_level_ids = {
    "SM - Main": 0x1,
#     "SM - Banjo's House": 0x8C,
    "MM - Main": 0x2,
    "MM - Ticker's Tower": 0xC,
    "MM - Mumbo's Skull": 0xE,
    "TTC - Main": 0x7,
    "TTC - Blubber's Ship": 0x5,
    "TTC - Nipper's Shell": 0x6,
    "TTC - Sandcastle": 0xA,
    "CC - Main": 0xB,
    "CC - Inside Clanker Blowhole": 0x21,
    "CC - Inside Clanker Belly": 0x22,
    "CC - Inside Clanker Gold Feathers": 0x23,
    "BGS - Main": 0xD,
    "BGS - Mr Vile": 0x10,
    "BGS - Tiptup Choir": 0x11,
    "BGS - Mumbo's Skull": 0x47,
    "FP - Main": 0x27,
    "FP - Boggy's Igloo": 0x41,
    "FP - Mumbo's Skull": 0x48,
    "FP - Christmas Tree": 0x53,
    "FP - Wozza's Cave": 0x7F,
    "GV - Gobi's Valley": 0x12,
    "GV - Puzzle Room": 0x13,
    "GV - King Sandybutt's Tomb": 0x14,
    "GV - Water Pyramid": 0x15,
    "GV - Rupee": 0x16,
    "GV - Jinxy": 0x1A,
    "MMM - Main": 0x1B,
    "MMM - Church": 0x1C,
    "MMM - Cellar": 0x1D,
    "MMM - Tumblar": 0x24,
    "MMM - Well": 0x25,
    "MMM - Dining Room": 0x26,
    "MMM - Egg Room": 0x28,
    "MMM - Note Room": 0x29,
    "MMM - Feather": 0x2A,
    "MMM - Secret Church Room": 0x2B,
    "MMM - Bathroom": 0x2C,
    "MMM - Bedroom": 0x2D,
    "MMM - Gold Feather Room": 0x2E,
    "MMM - Drainpipe": 0x2F,
    "MMM - Mumbo's Hut": 0x30,
    "MMM - Septic Tank": 0x8D,
    "RBB - Main": 0x31,
    "RBB - Engine Room": 0x34,
    "RBB - Big Fish Warehouse": 0x35,
    "RBB - Boat Room": 0x36,
    "RBB - First Blue Container": 0x37,
    "RBB - Third Blue Container": 0x38,
    "RBB - Sea-Grublin's Cabin": 0x39,
    "RBB - Kaboom's Room": 0x3A,
    "RBB - Mini Kaboom's Room": 0x3B,
    "RBB - Kitchen": 0x3C,
    "RBB - Navigation Room": 0x3D,
    "RBB - Second Blue Container": 0x3E,
    "RBB - Captain's Room": 0x3F,
    "RBB - Anchor Room": 0x8B,
    "CCW - Lobby": 0x40,
    "CCW - Spring Main": 0x43,
    "CCW - Summer Main": 0x44,
    "CCW - Fall Main": 0x45,
    "CCW - Winter Main": 0x46,
    "CCW - Spring Mumbo": 0x4A,
    "CCW - Summer Mumbo": 0x4B,
    "CCW - Fall Mumbo": 0x4C,
    "CCW - Winter Mumbo": 0x4D,
    "CCW - Summer Zubba Hive": 0x5A,
    "CCW - Spring Zubba Hive": 0x5B,
    "CCW - Fall Zubba Hive": 0x5C,
    "CCW - Spring Nabnut's House": 0x5E,
    "CCW - Summer Nabnut's House": 0x5F,
    "CCW - Fall Nabnut's House": 0x60,
    "CCW - Winter Nabnut's House": 0x61,
    "CCW - Winter Nabnut's Water Attic": 0x62,
    "CCW - Fall Nabnut's Water Attic": 0x63,
    "CCW - Winter Nabnut's Acorn Attic": 0x64,
    "CCW - Spring Whipcrack Room": 0x65,
    "CCW - Summer Whipcrack Room": 0x66,
    "CCW - Fall Whipcrack Room": 0x67,
    "CCW - Winter Whipcrack Room": 0x68,
    "GL - MM Puzzle/Entrance Room": 0x69,
    "GL - TTC Puzzle Room": 0x6A,
    "GL - CCW Puzzle Room": 0x6B,
    "GL - Pipe Room": 0x6C,
    "GL - TTC Entrance": 0x6D,
    "GL - GV Entrance": 0x6E,
    "GL - FP Entrance": 0x6F,
    "GL - CC Entrance": 0x70,
    "GL - Grunty Statue Room": 0x71,
    "GL - BGS Entrance": 0x72,
    "GL - Lava Room": 0x74,
    "GL - MMM Entrance": 0x75,
    "GL - 640 Note Door Room": 0x76,
    "GL - RBB Entrance": 0x77,
    "GL - MMM Puzzle": 0x78,
    "GL - CCW Entrance": 0x79,
    "GL - Coffin Room": 0x7A,
    "GL - Path To Furnace Fun": 0x80,
    "GL - Furnace Fun": 0x8E,
    "GL - Door Of Grunty Room": 0x93,
    "Final Battle": 0x90,
    }

non_softlock_start_level = [
    "SM - Main",
    "MM - Main", "MM - Ticker's Tower", "MM - Mumbo's Skull",
    "TTC - Main", "TTC - Nipper's Shell",
    "BGS - Main", "BGS - Tiptup Choir", "BGS - Mumbo's Skull",
    "FP - Main", "FP - Boggy's Igloo", "FP - Mumbo's Skull", "FP - Christmas Tree",
    "GV - Gobi's Valley", "GV - King Sandybutt's Tomb", "GV - Rupee", "GV - Jinxy",
    "GL - MM Puzzle/Entrance Room", "GL - TTC Puzzle Room",
    "GL - GV Entrance", "GL - FP Entrance", "GL - Grunty Statue Room", "GL - BGS Entrance", "GL - Lava Room",
    ]